import { build } from '../text.ts'

/* ------------------------------ Would You Rather ------------------------------ */
export const WYR = build('wyr', [
  ['COZY', 'Would you rather always cook together or always do the dishes together?', 'Always cook together 👩‍🍳|Always do dishes to music 🧼'],
  ['COZY', 'Would you rather get 100 sweet texts or 1 big surprise date?', '100 sweet texts 📱|One epic surprise date 🌃'],
  ['COZY', 'Would you rather be snowed in at a cabin or rained in at a beach hut?', 'Snowy cabin & fireplace 🏔️|Rainy beach hut 🌴'],
  ['COZY', 'Would you rather always hold hands or always cuddle during movies?', 'Always hold hands 🤝|Always cuddle on movie nights 🍿'],
  ['COZY', 'Would you rather relive our first date or fast-forward to our next trip?', 'Relive the first date 💖|Jump to the next dream trip ✈️'],
  ['COZY', 'Would you rather have free chai/coffee for life or free dessert for life?', 'Free chai & coffee forever ☕|Free dessert forever 🍨'],
  ['COZY', 'Would you rather dance together in the rain or stargaze on a warm night?', 'Dance in warm rain 💃|Stargaze under the sky 🌌'],
  ['COZY', 'Would you rather have {a} plan every date or have {b} plan every date?', '{a} plans every date 📅|{b} plans every date 📅'],
  ['COZY', 'Would you rather wake up to breakfast in bed or come home to a candlelit dinner?', 'Breakfast in bed 🥞|Candlelit dinner 🕯️'],
  ['COZY', 'Would you rather write love letters or record voice notes for each other?', 'Handwritten love letters 💌|Voice notes to replay 🎙️'],
  ['COZY', 'Would you rather have a private chef for a year or a personal masseuse for a year?', 'Private chef 🍷|Personal masseuse 💆'],
  ['COZY', 'Would you rather never argue again or never be bored again?', 'Never argue again 🕊️|Never be bored again 🎢'],
  ['WILD', 'Would you rather win a free trip anywhere now or one wish for our future?', 'Free trip anywhere ✈️|One wish for our future ✨'],
  ['WILD', 'Would you rather share one brain for a day or swap bodies for a day?', 'Share one brain 🧠|Swap bodies for 24 hours 🔄'],
  ['WILD', 'Would you rather live on a boat for a year or in a treehouse for a year?', 'A boat at sea ⛵|A treehouse in the forest 🌳'],
  ['WILD', 'Would you rather travel back to the past together or forward to the future?', 'The past ⏪|The future ⏩'],
  ['WILD', 'Would you rather be stuck on a deserted island with only each other or with all our friends?', 'Just the two of us 🏝️|All our friends 🎉'],
  ['WILD', 'Would you rather skydive together or scuba dive together?', 'Skydive 🪂|Scuba dive 🤿'],
  ['WILD', 'Would you rather move to a new country together or explore 10 cities at home?', 'Move abroad 🌍|Explore 10 cities at home 🚆'],
  ['WILD', 'Would you rather have unlimited flights for a year or a dream home for free?', 'Unlimited flights ✈️|A dream home 🏡'],
  ['WILD', 'Would you rather know the exact date of our next big celebration or every place we will travel to?', 'The exact big date 📅|Every place we will visit 🗺️'],
  ['WILD', 'Would you rather meet our future selves or our younger selves?', 'Our future selves 🔮|Our younger selves 🧒'],
  ['WILD', 'Would you rather have {a} choose our next holiday or have {b} choose it?', '{a} picks the holiday 🧳|{b} picks the holiday 🧳'],
  ['WILD', 'Would you rather live in a big city or a peaceful village together?', 'Big buzzing city 🌆|Peaceful village 🌾'],
  ['SILLY', 'Would you rather only speak in rhymes or sing every sentence for a day?', 'Only rhymes 🎤|Only singing 🎶'],
  ['SILLY', 'Would you rather have a pet dinosaur or a pet dragon?', 'A pet dinosaur 🦖|A pet dragon 🐉'],
  ['SILLY', 'Would you rather always laugh at the wrong moment or always cry at ads?', 'Laugh at the wrong time 😂|Cry at ads 😭'],
  ['SILLY', 'Would you rather have hands for feet or feet for hands?', 'Hands for feet 🖐️|Feet for hands 🦶'],
  ['SILLY', 'Would you rather wear matching pyjamas in public for a week or a couple\'s costume for a month?', 'Matching pyjamas in public 🐻|Couple\'s costume for a month 🦸'],
  ['SILLY', 'Would you rather have {a} sing every text message or {b} dance every greeting?', '{a} sings every text 🎤|{b} dances every greeting 🕺'],
  ['SILLY', 'Would you rather our life had a laugh track or a dramatic narrator?', 'A laugh track 😹|A dramatic narrator 🎙️'],
  ['SILLY', 'Would you rather eat only pizza for a year or only ice cream for a year?', 'Only pizza 🍕|Only ice cream 🍦'],
  ['SILLY', 'Would you rather be able to talk to animals or talk to plants?', 'Talk to animals 🐕|Talk to plants 🌱'],
  ['SILLY', 'Would you rather always be 10 minutes late or always be 20 minutes early?', 'Always 10 minutes late ⏰|Always 20 minutes early 🕗'],
  ['SILLY', 'Would you rather have a rewind button or a pause button for life?', 'A rewind button ⏪|A pause button ⏸️'],
  ['SILLY', 'Would you rather have no phone for a month or no Wi-Fi for a month?', 'No phone 📵|No Wi-Fi 📶'],
])

/* ------------------------------ Who's More Likely To ------------------------------ */
const AB = '{a}|{b}'
export const LIKELY = build('likely', [
  ['SWEET', 'Who is more likely to cry at a wedding?', AB],
  ['SWEET', 'Who is more likely to plan a surprise for the other?', AB],
  ['SWEET', 'Who is more likely to say "I love you" first after a fight?', AB],
  ['SWEET', 'Who is more likely to remember the tiniest detail about a date?', AB],
  ['SWEET', 'Who is more likely to write a love letter?', AB],
  ['SWEET', 'Who is more likely to give up their last bite of dessert?', AB],
  ['SWEET', 'Who is more likely to bring the other soup when they are sick?', AB],
  ['SWEET', 'Who is more likely to stay up late just to talk?', AB],
  ['SWEET', 'Who is more likely to tear up during a sad movie?', AB],
  ['SWEET', 'Who is more likely to keep every ticket and memory from trips?', AB],
  ['SWEET', 'Who is more likely to hug a stranger\'s baby or puppy?', AB],
  ['SWEET', 'Who is more likely to reach out first after a disagreement?', AB],
  ['FUNNY', 'Who is more likely to forget where they parked?', AB],
  ['FUNNY', 'Who is more likely to talk to themselves?', AB],
  ['FUNNY', 'Who is more likely to laugh at their own joke first?', AB],
  ['FUNNY', 'Who is more likely to burn water?', AB],
  ['FUNNY', 'Who is more likely to sing in the shower?', AB],
  ['FUNNY', 'Who is more likely to take 200 photos of one meal?', AB],
  ['FUNNY', 'Who is more likely to be late to their own birthday?', AB],
  ['FUNNY', 'Who is more likely to lose their phone while holding it?', AB],
  ['FUNNY', 'Who is more likely to binge a whole series in one night?', AB],
  ['FUNNY', 'Who is more likely to fall asleep in the car?', AB],
  ['FUNNY', 'Who is more likely to start a sentence and forget the ending?', AB],
  ['FUNNY', 'Who is more likely to become friends with the waiter?', AB],
  ['CHAOS', 'Who is more likely to book a trip on a whim?', AB],
  ['CHAOS', 'Who is more likely to get us lost on purpose?', AB],
  ['CHAOS', 'Who is more likely to adopt five pets at once?', AB],
  ['CHAOS', 'Who is more likely to get a spontaneous tattoo?', AB],
  ['CHAOS', 'Who is more likely to survive a zombie apocalypse?', AB],
  ['CHAOS', 'Who is more likely to win an argument with a stranger?', AB],
  ['CHAOS', 'Who is more likely to quit their job to follow a dream?', AB],
  ['CHAOS', 'Who is more likely to become famous?', AB],
  ['CHAOS', 'Who is more likely to try the weirdest item on the menu?', AB],
  ['CHAOS', 'Who is more likely to start a business at 2 AM?', AB],
  ['CHAOS', 'Who is more likely to break a world record?', AB],
  ['CHAOS', 'Who is more likely to talk their way out of a fine?', AB],
])

/* ------------------------------ Never Have I Ever ------------------------------ */
const HAVE = 'I have 🙋|Never 🙅'
export const NHIE = build('nhie', [
  ['SWEET', 'Never have I ever cried happy tears because of my partner.', HAVE],
  ['SWEET', 'Never have I ever kept a gift or note from my partner "just because".', HAVE],
  ['SWEET', 'Never have I ever rehearsed what to say before calling my partner.', HAVE],
  ['SWEET', 'Never have I ever secretly re-read our old messages.', HAVE],
  ['SWEET', 'Never have I ever planned our future in my head on a random day.', HAVE],
  ['SWEET', 'Never have I ever smiled at my phone like a fool because of a text.', HAVE],
  ['SWEET', 'Never have I ever told a friend "I think this is the one".', HAVE],
  ['SWEET', 'Never have I ever saved a song because it reminds me of my partner.', HAVE],
  ['SWEET', 'Never have I ever stayed up just to say goodnight.', HAVE],
  ['SWEET', 'Never have I ever wanted to freeze a moment with my partner forever.', HAVE],
  ['SWEET', 'Never have I ever taken a photo of my partner when they were not looking.', HAVE],
  ['SWEET', 'Never have I ever cancelled plans to spend time with my partner.', HAVE],
  ['FUN', 'Never have I ever stalked an ex\'s profile.', HAVE],
  ['FUN', 'Never have I ever pretended to like a movie my partner picked.', HAVE],
  ['FUN', 'Never have I ever lied about being on my way when I had not left yet.', HAVE],
  ['FUN', 'Never have I ever eaten my partner\'s food and blamed someone else.', HAVE],
  ['FUN', 'Never have I ever googled my symptoms and panicked.', HAVE],
  ['FUN', 'Never have I ever laughed at a joke I did not understand.', HAVE],
  ['FUN', 'Never have I ever sent a text to the wrong person.', HAVE],
  ['FUN', 'Never have I ever forgotten an important date.', HAVE],
  ['FUN', 'Never have I ever fallen asleep during a call with my partner.', HAVE],
  ['FUN', 'Never have I ever walked into a glass door or wall.', HAVE],
  ['FUN', 'Never have I ever ordered food and pretended I cooked it.', HAVE],
  ['FUN', 'Never have I ever sung along to a song and got every lyric wrong.', HAVE],
  ['SPICY', 'Never have I ever had a crush on someone I should not have.', HAVE],
  ['SPICY', 'Never have I ever flirted just to get something free.', HAVE],
  ['SPICY', 'Never have I ever sent a message and instantly regretted it.', HAVE],
  ['SPICY', 'Never have I ever dressed up just to get my partner\'s attention.', HAVE],
  ['SPICY', 'Never have I ever fantasised about a romantic getaway with just the two of us.', HAVE],
  ['SPICY', 'Never have I ever kissed someone on the first date.', HAVE],
  ['SPICY', 'Never have I ever pretended not to be jealous when I was.', HAVE],
  ['SPICY', 'Never have I ever shared a kiss in a public place.', HAVE],
  ['SPICY', 'Never have I ever had a butterflies-in-the-stomach moment with my partner recently.', HAVE],
  ['SPICY', 'Never have I ever tried to make my partner jealous on purpose.', HAVE],
  ['SPICY', 'Never have I ever written a flirty text and deleted it.', HAVE],
  ['SPICY', 'Never have I ever wanted to skip plans just to stay in with my partner.', HAVE],
])

/* ------------------------------ Finish the Sentence ------------------------------ */
export const SENTENCE = build('sentence', [
  ['SWEET', 'My favourite thing about {partner} is…'],
  ['SWEET', 'I feel closest to {partner} when…'],
  ['SWEET', 'The moment I knew I was falling for {partner} was…'],
  ['SWEET', 'One thing {partner} does that always makes me smile is…'],
  ['SWEET', 'I am most proud of {partner} for…'],
  ['SWEET', 'Something I never say enough to {partner} is…'],
  ['SWEET', 'My favourite memory with {partner} is…'],
  ['SWEET', 'I love how {partner} makes me feel…'],
  ['SWEET', 'If I could give {partner} one gift that money cannot buy, it would be…'],
  ['SWEET', 'The little thing {partner} does that I secretly adore is…'],
  ['DEEP', 'I feel safest with {partner} when…'],
  ['DEEP', 'Something I want us to do more of together is…'],
  ['DEEP', 'A dream I have for us is…'],
  ['DEEP', 'One thing I want {partner} to know about me is…'],
  ['DEEP', 'A fear I sometimes have about us is…'],
  ['DEEP', 'I feel most understood by {partner} when…'],
  ['DEEP', 'What I need most from {partner} when I am stressed is…'],
  ['DEEP', 'The best advice {partner} ever gave me was…'],
  ['DEEP', 'I want us to be the kind of couple that…'],
  ['DEEP', 'Something {partner} taught me without meaning to is…'],
  ['FUN', 'The funniest thing {partner} has ever done is…'],
  ['FUN', 'If {partner} were a movie, it would be…'],
  ['FUN', 'The song that reminds me most of {partner} is…'],
  ['FUN', 'If {partner} were an animal, they would be a… because…'],
  ['FUN', 'My favourite silly nickname for {partner} is…'],
  ['FUN', 'The most {partner} thing ever is…'],
  ['FUN', 'If we opened a restaurant, {partner} would be in charge of…'],
  ['FUN', 'The weirdest thing I love about {partner} is…'],
  ['FUN', 'If we were characters in a sitcom, our episode would be called…'],
  ['FUN', 'My dream date with {partner} would be…'],
])
